CREATE DATABASE EVALUATION;

USE EVALUATION;

CREATE TABLE REPLACEMENT_PART(
	ID INT NOT NULL AUTO_INCREMENT,
	SERIAL_NUMBER VARCHAR(300) NOT NULL,
	WIDTH DOUBLE(100, 2) NOT NULL,
	HEIGHT DOUBLE(100, 2) NOT NULL,
	DEPTH DOUBLE(100, 2) NOT NULL,
	WEIGHT DOUBLE(100, 2) NOT NULL,
	PRIMARY KEY (ID)
);
