CREATE DATABASE EVALUATION;

USE EVALUATION;

CREATE TABLE PRODUCT(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	PRICE DOUBLE(100, 2) NOT NULL,
	CATEGORY VARCHAR(100),
	WEIGHT DOUBLE(100, 2) NOT NULL,
	PRIMARY KEY (ID)
);
