CREATE DATABASE EVALUATION;

USE EVALUATION;

CREATE TABLE PERSON(
	ID INT NOT NULL AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	BIRTH_DATE DATE NOT NULL,
	BIRTH_PLACE VARCHAR(100) NOT NULL,
	JOB VARCHAR(100),
	PRIMARY KEY (ID)
);
